---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0


# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization

searchguard.allow_unsafe_democertificates: true

searchguard.restapi.roles_enabled: ["sg_all_access"]

searchguard.ssl.transport.pemcert_filepath: ./certs/esnode.pem
searchguard.ssl.transport.pemkey_filepath: ./certs/esnode-key.pem
searchguard.ssl.transport.pemtrustedcas_filepath: ./certs/root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false


searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de