version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports: 
      - 27017:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  elasticsearch:
    image: teamsonic/elasticsearch-search-guard:6.4.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./var/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/config/sg_internal_users.yml:/usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_internal_users.yml
      - ./elasticsearch/config/sg_config.yml:/usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_config.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  dashboard:
      image: 'teamsonic/grabid-dashboard'
      ports:
          - "3000:80"
      depends_on:
          - elasticsearch
  rabbit.docker:
   image: rabbitmq:3.7.8-management-alpine
   restart: always     
   hostname: rabbit.docker
   ports:
      - "15672:15672"
      - "5672:5672"
  refiner:
    image: grabid/refiner:local
    build:     
      context: ./src/Refiner
    depends_on: 
      - rabbit.docker  
    restart: always
  logger:
    image: grabid/logger:local
    build:     
      context: ./src/Logger
    depends_on: 
      - rabbit.docker  
    restart: always
  ingestion:
    image: grabid/ingestion:local
    build:      
      context: ./src/Ingestion  
    depends_on: 
      - rabbit.docker
    restart: always