version: "3"
services:
  rabbit.docker:
   image: rabbitmq:3.7.8-management-alpine
   restart: always     
   hostname: rabbit.docker
   ports:
      - "15672:15672"
      - "5672:5672"
  refiner:
    image: grabid/refiner:local
    build:     
      context: ./src/Refiner
    depends_on: 
      - rabbit.docker  
    restart: always
  logger:
    image: grabid/logger:local
    build:     
      context: ./src/Logger
    depends_on: 
      - rabbit.docker  
    restart: always
  ingestion:
    image: grabid/ingestion:local
    build:      
      context: ./src/Ingestion  
    depends_on: 
      - rabbit.docker
    restart: always

  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

volumes:
  mongodb_master_data:
    driver: local