version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-tier
    hostname: mongo
    environment:
      - MONGODB_USERNAME=defaultUser
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=refinerCache